' <auto-generated />
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports VazorTopShelf.Db

Namespace Global.VazorTopShelf.Db.Migrations
    <DbContext(GetType(Context))>
    Partial Class ContextModelSnapshot
        Inherits ModelSnapshot

        Protected Overrides Sub BuildModel(modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15")

            modelBuilder.Entity("VazorTopShelf.Db.Models.Contact",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Email").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(50).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("FirstName").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(10).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("LastName").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(10).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("PhoneArea").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(3).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("PhonePrefix").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(3).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.Property(Of String)("PhoneSuffix").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(4).
                        HasColumnType("TEXT").
                        HasDefaultValue("")

                    b.HasKey("Id")

                    b.HasIndex("FirstName")

                    b.HasIndex("LastName")

                    b.HasIndex("FirstName", "LastName")

                    b.ToTable("Contacts")
                End Sub)
        End Sub
    End Class
End Namespace
